- name: install nginx in node server
  hosts: node
  become: yes
  tasks:
  - name : Install nginx in node server
    ansible.builtin.package:
      name: nginx
      state: installed
  - name: Start the nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes