- name: Variables from files
  hosts: local
  connection: local
  vars_files:
  - course.yaml
  tasks:
  - name: print variables from the file
    ansible.builtin.debug:
      msg: "I am learning {{ Course }}, With duration of {{ Duration }}, want to complete it by {{ End }}"