- name: Data types
  hosts: local
  connection: local
  vars:
    Course: "DevSecOps with AWS" #String
    Duration: 120 
    IS_LIVE: true #boolean
    Concepts: #list #The o/p come as []
    - linux
    - shell
    - ansible
    Tools: #map or object #The o/p come as {}
      CI: Jenkins
      Scripting: "Shell, ansible"
  tasks:
  - name: print the data types
    ansible.builtin.debug:
      msg: "Iam learning {{ Course }}, with duration of {{ Duration }}hrs, it is live sessions {{ IS_LIVE }}, conecpts are {{ Concepts }}, Tools till used are {{ Tools }}"