- name: Conditons Concepts
  hosts: local
  connection: local
  vars:
    NUMBER: 169
  tasks:
  - name: print the number less than 100
    ansible.builtin.debug:
      msg: "Given number {{ NUMBER }} is less than 100"
    when: NUMBER < 100

  - name: print the number greater than 100
    ansile.builtin.debug:
      msg: "Given number {{ NUMBER }} is greater than 100"
    when: NUMBER > 100