- name: Install Packages
  hosts: frontend
  become: yes
  tasks:
  - name: Installing the packages in loop
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop:
    - mysql
    - nginx
    - nodejs