- name: Functions converting string into list
  hosts: local
  connection: local
  vars:
    persons: "Anil, kumar, Naidu"
  tasks:
  - name: Print undefined variable
    ansible.builtin.debug:
      msg: "Hello, {{ person | default('Attada') }}"
  - name: Print names
    ansible.builtin.debug:
      msg: "This is {{ persons | split(',')}}"