- name: shell vs command
  hosts: frontend
  tasks:
  - name: redirect the output to a file
    #ansible.builtin.command: "ls -ltr > /tmp/output.txt" #This won't work to get inside the server.
    ansible.builtin.shell: "ls -ltr > /tmp/output.txt" #This will go into the server and save files.
    #For simple tasks command is used for complex tasks shell is preffered as it access environment.

  - name: ls output file using command module
    ansible.builtin.command: "ls -ltr"
    register: command_output #In command module output is saved in register

  - name: print output
    ansible.builtin.debug:
      msg: "{{ command_output }}"