- name: create ec2 and r53 records
  hosts: local
  connetion: local
  vars:
    instances:
    - mysql
    - backend
    - frontend
    subnet_id: subnet-0d0203f58a2bb01c7
    sg_id: sg-06f23152b42979b41
    ami_id: ami-0220d79f3f480ecf5
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: "{{ subnet_id }}"
      instance_type: t3.micro
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      tags:
        Name: "{{ item }}"
    loop: "{{ instances }}"
    
 