[frontend]
; 172.31.22.27 Course=DevSecOps, Timing=Evenings 
#This is for passing variables from inventory file.

[local]
localhost

; [local:vars]
; GREETINGS=This is from Inventory
;  Trainer=Own
;  Friend=Ravi's